dubbo:
    application:
        name: order-service-consumer
    monitor:
        protocol: registry
#    protocol:
#        name: dubbo
#        port: 20888
    registry:
        address: zookeeper://127.0.0.1:2181
    consumer:
        check: false
server:
    port: 8088
spring:
    datasource: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://root@localhost:3306/example?serverTimezone=Asia/Taipei&useSSL=false&allowPublicKeyRetrieval=true
        name: root
        password: root